### PR TITLE
Rounding fix

### PR DESCRIPTION
**Pull request by LauraSchoenhals**
I changed the code so it does not round the data. This avoids a lot of issues. 

In my specific case, the program could not find my step cycles, and would only run at 100Hz, which was obviously incorrect. Changing it to int allowed me to use 250Hz for the bottom image. 

Before fix: 
image

After fix:

ID 303 - Run 1 - Ankle Angle by Time

### CODE REVIEW

**Comment by LauraSchoenhals** [comment]
I changed it to stop rounding the labels as well (second commit), but then that covers up the data, so the third commit undoes that change.

**Comment by mahan-hosseini** [comment]
Thank you very much for this! Certainly a much nicer way of approaching this issue than rounding and matching indices as I was doing previously. In case you'll see it - I'll add some user-error-handling stuff in the next commits but nothing substantial.

**Comment by LauraSchoenhals** [comment]
When I tried it originally, I was actually trying with the sampling rate at 200Hz because that is what I thought our data was. At that point, I configured the annotation table with 3 decimal places accordingly. When I did this, only one step cycle was matched. So then I used 100Hz, which ran regardless of rounding to 2 or 3 decimal places, but was not accurate to my data. 

Once I added my change, I was able to run it with 200Hz sampling and could see this was also not the correct rate for my data, so I changed it to 250Hz which looked more correct.

**Comment by mahan-hosseini** [comment]
Ah okay I see, thank you for the clarification 😊

**Pull request merged**
